# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here: https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"

# A version range to match for said mod loader
loaderVersion="${loader_version_range}"

# The license for your mod
license="${mod_license}"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

description='''
Example mod description.
'''

# NeoForge dependency
[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

# Minecraft dependency
[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# LambDynamicLights dependency
[[dependencies."${mod_id}"]]
modId="lambdynlights"
type="required"
versionRange="[4.5.0,)"
ordering="NONE"
side="CLIENT"

# [[mixins]]
# config="${mod_id}.mixins.json"

# [[accessTransformers]]
# file="META-INF/accesstransformer.cfg"

# [features.${mod_id}]
# openGLVersion="[3.2,)"